name: Docs
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        sudo apt-get install -y pandoc
        python -m pip install --upgrade pip
        python -m pip install ".[docs]"
    - name: Run notebooks
      run: |
        jupytext --to ipynb --pipe black --execute docs/markdown/public_data_access.md
        jupytext --to ipynb --pipe black --execute docs/markdown/detector_model.md
        jupytext --to ipynb --pipe black --execute docs/markdown/source_model.md
        jupytext --to ipynb --pipe black --execute docs/markdown/simulation.md
        jupytext --to ipynb --pipe black --execute docs/markdown/point_source_likelihood.md
        jupytext --to ipynb --pipe black --execute docs/markdown/point_source_analysis.md
        jupytext --to ipynb --pipe black --execute docs/markdown/events.md
        mv docs/markdown/*.ipynb docs/notebooks

    - name: Generate API docs
      run: |
        sphinx-apidoc -f -e -o docs/api icecube_tools
        sphinx-build -M html docs/ docs/_build

    - name: Setup pages
      uses: actions/configure-pages@v6

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: './docs/_build/html'
        
  deploy:
    name: Deploy docs
    if: ${{ github.event_name == 'push' && github.ref_name == 'master' }}
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5